sonar.projectKey=VijayPatil0046_devsecops_project_cloud
sonar.organization=VijayPatil0046
sonar.projectName=devsecops_project_cloud
sonar.sources=api.py,data_loader.py,evaluate.py,feature_engineering.py,main.py,model.py,vault_bootstrap.py,frontend/green-cloud-guardian/src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=frontend/green-cloud-guardian/node_modules/**,frontend/green-cloud-guardian/dist/**,.venv/**,venv/**,.git/**,data/**,outputs/**,**/__pycache__/**,*.pkl
sonar.python.version=3.11
